
x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}
  build:
    context: .
    dockerfile: Dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres/${PG_DB}
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
  volumes:
    - ./dags:/opt/airflow/dags:ro
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins:ro
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy
    minio:
      condition: service_healthy
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER} -d ${PG_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    env_file:
      - .env
    container_name: airflow_webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    networks:
      - airflow-network

  airflow-scheduler:
    <<: *airflow-common
    env_file:
      - .env
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    networks:
      - airflow-network

  airflow-init:
    <<: *airflow-common
    env_file:
      - .env
    container_name: airflow-init
    entrypoint: ["/bin/bash", "-c"]
    command: >
      airflow db init &&
      airflow users create \
        --username ${_AIRFLOW_WWW_USER_USERNAME:-admin} \
        --password ${_AIRFLOW_WWW_USER_PASSWORD:-admin123} \
        --firstname Admin \
        --lastname Admin \
        --role Admin \
        --email admin@example.com
    environment:
      <<: *airflow-common-env
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      FILE_NAME: ${FILE_NAME}
      _AIRFLOW_DB_UPGRADE: true
    networks:
      - airflow-network

volumes:
  pg-data:
    name: pg-data
  minio-data:
    name: minio-data

networks:
  airflow-network:
    name: airflow-network
    driver: bridge