version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9090"
    volumes:
      - ./minio-data:/data
  postgres:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: dwh
      ports:
        - "5433:5432"
      volumes:
        - ./pg-data:/var/lib/postgresql/data